apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadvcgk9026-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadvcgk9026-tenant-component
    app.kubernetes.io/part-of: loadvcgk9026-tenant-app
  name: loadvcgk9026-tenant-component
  namespace: loadvcgk9026-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadvcgk9026-tenant-component
    weight: null
status: {}
